### ISSUE TITLE
Options page says user must log in to set preferences. (was 'Doesn't seem to work in Canada')

### ISSUE THREAD

**Issue by bewuethr** [jaredsohn/flix_plus#5]
I keep getting the
> You must log in to Netflix prior to setting preferences.

message. I've reloaded the page, refreshed the cache, switched Netflix profiles, checked the Chrome console for errors &ndash; nothing. The Netflix domain here is .com.

**Comment by jaredsohn** [comment]
It shows that error message if the following line is run from the console on the options page: 

    chrome.storage.local.get("flix_plus profilename", function(items) { console.log(items); })

and it returns an empty object.

Normally, when you visit most Netflix pages after you are logged in, it will set that field for you based on the profile name field in the HTML. (you can compare by running:

    document.getElementsByClassName("acct-menu-dropdown-trigger")[0].innerText

from the console.)

If you want to "cheat", run this line:

    chrome.storage.local.set({"flix_plus profilename" : "myprofilename"}, function(items) { console.log(items); })

from the options page, where 'myprofilename' is your profile name.

**Comment by bewuethr** [comment]
Bear with the JavaScript illiterate that is me.

    chrome.storage.local.get("flix_plus profilename", function(items) { console.log(items); })

gives me

> TypeError: Cannot read property 'local' of undefined

and

    document.getElementsByClassName("acct-menu-dropdown-trigger")[0].innerText

results in

> TypeError: Cannot read property 'innerText' of undefined

I can find my user name in the HTML source, though. Trying to set it manually with

    chrome.storage.local.set({"flix_plus profilename" : "myprofilename"}, function(items) { console.log(items); })

(with `myprofilename` properly replaced) gives me

> TypeError: Cannot read property 'local' of undefined

**Comment by jaredsohn** [comment]
Seeing the error "TypeError: Cannot read property 'innerText' of undefined" (assuming you were on the right page), would explain why it is not reading the profile name.  This could be because you are in Canada or could be a result of Netflix rolling out changes to you that I don't see when I develop (they do this frequently, although I haven't been aware of it breaking things for the extension too often).  If you want to help isolate this, send me a copy of the HTML of the homepage (images not needed) or at least the HTML nearby where your profile name shows up in the source. You could also try turning off test participation in Your Account.

The other errors shouldn't show if you try it from the options page or from "Inspect views: forge.html" from chrome://extensions/.  But unless you fix the earlier problem, your settings won't be honored anyway (and once you do fix it, you shouldn't need to do these workarounds.)

Jared
jared.sohn at lifehacker.com

**Comment by bewuethr** [comment]
It was the test participation &ndash; without it, it works. I'll send you the HTML of the not working one.

**Comment by jaredsohn** [comment]
Thanks for following up; now closing the issue.
