### ISSUE TITLE
Feature Request: Fade by MPAA rating

### ISSUE THREAD

**Issue by cognifloyd** [jaredsohn/flix_plus#7]
I want a way to say that I'm not interested in all movies that are rated R.

Could you add the option to Fade/Tint movies based on their rating? Perhaps it could be part of the "not interested or marked one star" script (fade_rated.js).

Or perhaps another script could automatically mark all movies of a given rating as "not interested". Then, they would be tinted by fade_rated.js without my manually marking them as not interested.

**Comment by jaredsohn** [comment]
We don't do this because we don't have a current way of looking up the rating by knowing just the title and Netflix id.  It could be found by extracting it after details are shown the first time or by using the rotten tomatoes/imdb lookup (but that also requires looking at details so that it can get the year and whether it is a movie or a tv series.)

If you want to write your own script to generate the data yourself, the list of netflix ids for rated and watched are stored in the localstorage of Netflix's site. Note that the data gets regenerated from scratch every once in awhile which could wipe out your data, but the date used to determine when that happens is also in localstorage so you could modify that as well.  (The main reason to allow it to regenerate data is it allows removing entries that a user manually deleted.)
