### ISSUE TITLE
Fade out/tint watched/rated not working

### ISSUE THREAD

**Issue by Gabriel-p** [jaredsohn/flix_plus#9]
I have the options `Fade out/tint watched` and `Fade out/tint rated` selected, configured as shown below.

![captura de pantalla de 2015-11-21 00 09 57](https://cloud.githubusercontent.com/assets/6054951/11316396/4819d694-8fe4-11e5-8681-0e7445ba710b.png)

Neither seems to work. Both watched and rated movies are shown with no changes.

Also, what is the "not interested" option? I haven't seen such an option anywhere.

Chrome v 46.0.2490.86 (64-bit)

**Comment by jaredsohn** [comment]
A fix for this coming soon (either tonight or tomorrow). The problem was that Netflix recently changed how they identify poster elements within the DOM, so that fading out/tinting rated and watched would update nothing and fading out/tinting duplicates would affect all posters. Also, exporting My List won't work in Netflix Suggests mode.

When Netflix made an update this past summer, they mostly removed the ability to rate posters as 'not interested', although you can still do so at https://www.netflix.com/MoviesYouveSeen and maybe some other places. Thus, the extension was updated to treat shows rated as 'one star' in the same way as 'not interested' ones.

**Comment by jaredsohn** [comment]
I just posted Flix Plus v3.12 with a fix; hope that works for you.
